// <auto-generated />
namespace mksolucion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class actualizacionMensajeRapidos20170622 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(actualizacionMensajeRapidos20170622));
        
        string IMigrationMetadata.Id
        {
            get { return "201706222118304_actualizacionMensajeRapidos20170622"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
