// <auto-generated />
namespace mksolucion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AcualizacionMensajePredefinidos20160616 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AcualizacionMensajePredefinidos20160616));
        
        string IMigrationMetadata.Id
        {
            get { return "201706161357493_AcualizacionMensajePredefinidos20160616"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
