// <auto-generated />
namespace mksolucion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CreacionTablaestadocompletado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreacionTablaestadocompletado));
        
        string IMigrationMetadata.Id
        {
            get { return "201705121444213_CreacionTablaestadocompletado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
