// <auto-generated />
namespace mksolucion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class actualizacion_remitente_contacto1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(actualizacion_remitente_contacto1));
        
        string IMigrationMetadata.Id
        {
            get { return "201707071441070_actualizacion_remitente_contacto1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
