// <auto-generated />
namespace mksolucion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class actualizacionusuariocontacto_201707032 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(actualizacionusuariocontacto_201707032));
        
        string IMigrationMetadata.Id
        {
            get { return "201707031621058_actualizacionusuariocontacto_201707032"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
